### ISSUE TITLE
Berlin for travel

### ISSUE THREAD

**Issue by JBB** [cs210/ViewR#4]
Hi folks,

Realities.io can meet with you in Berlin the week of March 23 or March 30.  They can do in person training and perform some captures with you in the field.  This is a GREAT option in terms of learning, so if you can get excited about going to Berlin (and then Europe to whatever degree you wish) this would be a slam dunk.

Jay

**Comment by JasonZheng20** [comment]
We reached out the the Realities.io team and tentatively decided that we will be visiting them in Berlin on March 20.
