### ISSUE TITLE
Desktop computer and SD card needed

### ISSUE THREAD

**Issue by tareshsethi** [cs210/ViewR#5]
Hi Jay and Swathi,

Could you find us access to a desktop computer with a hard drive and gpu - we tried all of the unused ones in the loft and each was missing one or the other.

Also, we talked about this in our SGMs yesterday, but could you also find us an sd card for the camera, preferably 128gb as recommended by realities.io?

Thanks so much!

**Comment by swathiiyer2** [comment]
Hi guys, the SD cards came in yesterday, and will be in the loft. Are cloud GPUs an option?

**Comment by tareshsethi** [comment]
Hey swathi, thanks! - we'll collect the sd card today. We will need a computer with an in-place gpu so that we can run VR in unity

**Comment by swathiiyer2** [comment]
Re desktops: A few other teams have gotten their desktops working (including the other VR team). Maybe reach out to them to ask if you can share their workspace?

**Comment by JBB** [comment]
Hi team,
I think you should have your own workstation.  There are a few options available in the Loft right now that will work.  

Preferred Option 1:  There are two Alienware (the triangular looking ones) workstations under the center table that goes around the pillars.  You can get one of those to work by doing one of the following:
a. Take the video card from one and put it in the other (easier).
b.  Take the power supply from the one wo/ the video card and put it in the other
Option a is likely easier.  (harder; more cords/screws)
You do not need tools to get inside the machine.  The side of the Alienware workstations comes off easily after you slide a switch near the top.  You may need a screwdriver to get the video card out (we have a toolset in the loft)

Option 2:  The computer in the corner near the MSFT Surface Hub works with the following two caveats; it needs a mouse and the C drive needs to be cleaned up a bit, so there is some space for new system files/drivers, etc.  I believe the cs210student/cs210a combo gets you into that one.  The Axles team did set that one up before and may need their own workstation in the future, but we can cross that bridge when they come to it.

Special option 3: If you try #1 and get it working, if you run into any future problems we'll get you a new workstation.

**Comment by derekahuang** [comment]
Computer is up and running
